{"name": "test_add2[【类型】输入英文，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：30和t开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 52, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660805207745, "stop": 1660805207745}], "attachments": [{"name": "log", "source": "b566177e-3091-422f-95bc-0b536095eac4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3c599108-08bb-4445-b515-706fc6fe54f4-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "75acf117-9863-41db-a127-73269afadbd2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "30"}, {"name": "y", "value": "'t'"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660805207744, "stop": 1660805207746, "uuid": "84b94973-d501-4959-8094-56d02d835159", "historyId": "3361d8b8cf961ff51186e6289124baa5", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "feature", "value": "加法计算模块"}, {"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "7552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}