{"name": "test_add2[【类型】输入空格，给出提示信息1]", "status": "passed", "steps": [{"name": "步骤一： 和3.14开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 53, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660806013581, "stop": 1660806013581}], "attachments": [{"name": "log", "source": "5a59061c-c76d-4bda-bbf3-67ec25dacf11-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "8cc95bcb-855c-411a-8c78-d85dd238ac37-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "542fd843-79ab-47e4-8a5d-77c432ad8130-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "' '"}, {"name": "y", "value": "3.14"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660806013581, "stop": 1660806013581, "uuid": "9c4c85f8-fe72-4c06-9c6d-f9cd6d1e2cb5", "historyId": "e47079f6b402f00730355da220abcb87", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "feature", "value": "加法计算模块"}, {"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "21868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}