{"name": "test_add2[【类型】输入为空，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：-3和开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 52, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660804986857, "stop": 1660804986857}], "attachments": [{"name": "log", "source": "1dac4bb2-ecc8-4122-a7bd-93eedbe51f8d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "52b50b3a-5d46-4992-ad1d-b5ffdceeb9a5-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d11f5502-c244-4616-91c1-36f4e98017fb-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "-3"}, {"name": "y", "value": "''"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660804986857, "stop": 1660804986857, "uuid": "85e1910a-cc75-4e64-9dd0-b49b61cc90b2", "historyId": "0412f9eaf97e435531107a7fcdc7ef69", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "13372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}