{"name": "test_add2[【类型】输入中文，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：4和字开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 53, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660806013544, "stop": 1660806013544}], "attachments": [{"name": "log", "source": "72bc9798-dd98-4f8d-9232-7fffca0a2901-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "8e910318-9bf9-41f7-a930-34f8fb11cebf-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "2c7b0341-e924-47bd-a923-0ce97b7cb85c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "4"}, {"name": "y", "value": "'字'"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660806013544, "stop": 1660806013545, "uuid": "b28cf390-871a-40e2-b882-1b90b91e115b", "historyId": "f18f3197389620d993b415e56fa662e5", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "feature", "value": "加法计算模块"}, {"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "21868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}