{"name": "test_add2[【类型】输入英文，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：30和t开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 53, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660806013555, "stop": 1660806013555}], "attachments": [{"name": "log", "source": "7e4229d7-45ad-48b2-b2e5-17c5d968fda3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "a71802d3-6cc0-482f-955d-249e86fb57c6-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "2afb6e56-6fb2-4f69-9c69-7e0d93bbb507-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "30"}, {"name": "y", "value": "'t'"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660806013554, "stop": 1660806013555, "uuid": "2198fdea-b146-4dd9-b6c7-a34d00f24454", "historyId": "3361d8b8cf961ff51186e6289124baa5", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "feature", "value": "加法计算模块"}, {"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "21868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}