{"name": "test_add2[【类型】输入中文，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：4和字开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 52, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660804986823, "stop": 1660804986823}], "attachments": [{"name": "log", "source": "4b30b5aa-bf31-496f-8670-67b597ddc51c-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "c049c1e1-a3a9-41a0-8ae8-4fa309770ccb-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "298a6bd1-de39-4c33-8fba-4507601b9894-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "4"}, {"name": "y", "value": "'字'"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660804986823, "stop": 1660804986824, "uuid": "7063b771-4b5b-43cc-aa6d-1741de37633b", "historyId": "f18f3197389620d993b415e56fa662e5", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "13372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}