{"name": "test_add2[【类型】输入英文，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：30和t开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 52, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660804986835, "stop": 1660804986835}], "attachments": [{"name": "log", "source": "cef7cb60-9b95-41df-9562-9771cba7b612-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "ac25d393-225e-4c26-a757-925438774b0e-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "790ee47a-0122-41e5-890b-9e2000f9f61b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "30"}, {"name": "y", "value": "'t'"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660804986835, "stop": 1660804986836, "uuid": "b657dd68-74e3-4eb3-b8f6-ef2f10ce587d", "historyId": "3361d8b8cf961ff51186e6289124baa5", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "13372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}