{"name": "test_add2[【类型】输入空格，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：-90和 开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 52, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660804986868, "stop": 1660804986868}], "attachments": [{"name": "log", "source": "94cf4c50-8f30-41d6-9b9d-fd88b7be7b77-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "801b5a41-50eb-4ca3-ac0a-f0e098db7f56-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "737ae6fe-f703-4012-808d-46834ad88dd2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "-90"}, {"name": "y", "value": "' '"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660804986868, "stop": 1660804986868, "uuid": "a58e854c-2a41-41a5-965e-22dc93a11ba0", "historyId": "ac1d2ef63c92ef71d0fd1a77add8baf1", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "13372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}