{"name": "test_add2[【类型】输入特殊字符，给出提示信息2]", "status": "passed", "steps": [{"name": "步骤一：21.45和@开始计算，预期应等于参数大小超出范围，打印<ExceptionInfo for raises contextmanager>", "status": "broken", "statusDetails": {"message": "TypeError: '>' not supported between instances of 'str' and 'int'\n", "trace": "  File \"D:\\zj\\PycharmProjects\\study202208\\study0818\\test\\test_calculate.py\", line 53, in test_add2\n    result=self.cal.add(x,y)\n  File \"D:\\zj\\PycharmProjects\\study202208\\script\\calculator.py\", line 4, in add\n    if a > 99 or a < -99 or b > 99 or b < -99:\n"}, "start": 1660806013565, "stop": 1660806013565}], "attachments": [{"name": "log", "source": "1a7d47dc-f7fc-4cb2-a474-b896638f5876-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "d08fc572-8f6d-4c88-93af-3ecb0f18535b-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "f0062727-9ca0-45d1-aa05-0a7d4997ba44-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "x", "value": "21.45"}, {"name": "y", "value": "'@'"}, {"name": "expect", "value": "'参数大小超出范围'"}], "start": 1660806013565, "stop": 1660806013565, "uuid": "b1217e65-2318-4296-8609-47b4160dd8d1", "historyId": "ad09060ab4e52a6c2d71173ec5c04aa6", "testCaseId": "c1fd4152c4894ab47d6f7448dc1c5bcf", "fullName": "study0818.test.test_calculate.TestAdd#test_add2", "labels": [{"name": "feature", "value": "加法计算模块"}, {"name": "story", "value": "加法报错用例"}, {"name": "tag", "value": "P2"}, {"name": "parentSuite", "value": "study0818.test"}, {"name": "suite", "value": "test_calculate"}, {"name": "subSuite", "value": "TestAdd"}, {"name": "host", "value": "LAPTOP-BEO6NH7O"}, {"name": "thread", "value": "21868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "study0818.test.test_calculate"}]}